# Generated by Django 5.0.6 on 2024-07-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prix',
            field=models.FloatField(default=25),
            preserve_default=False,
        ),
    ]
