# Generated by Django 5.0.6 on 2024-07-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_article_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prix',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
