# Generated by Django 5.0.6 on 2024-07-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_article_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
