# Generated by Django 5.0.6 on 2024-07-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_article_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prix_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
