# Generated by Django 5.0.6 on 2024-07-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_article_prix_final_alter_article_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='prix_final',
        ),
    ]
