name: ciTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code
      id: lint
      run: |
        pip install flake8
        flake8 . > flake8_errors.txt

    - name: Notify Slack about Linting Errors
      if: failure() # Notify only if linting fails
      run: |
        lint_errors=$(cat flake8_errors.txt || echo "No linting errors")
        curl -X POST -H 'Content-type: application/json' \
        --data "{\"text\":\"Linting completed with errors: \n${lint_errors}\"}" \
        ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Run tests
      id: test
      run: |
        pip install pytest
        pytest > pytest_output.txt

    - name: Notify Slack about Testing Errors
      if: failure() # Notify only if testing fails
      run: |
        test_errors=$(cat pytest_output.txt || echo "No test errors")
        curl -X POST -H 'Content-type: application/json' \
        --data "{\"text\":\"Testing completed with errors: \n${test_errors}\"}" \
        ${{ secrets.SLACK_WEBHOOK_URL }}

  
