name: ciTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code
      run: |
        pip install flake8
        python scripts/lint_script.py
        
    - name: Run tests
      run: |
        pip install pytest
        pytest

    - name: Notify Slack about Linting Errors
      if: always()
      run: |
        lint_errors=$(cat flake8_errors.txt)
        curl -X POST -H 'Content-type: application/json' \
        --data "{\"text\":\"Linting completed with errors: \n${lint_errors}\"}" \
        ${{ secrets.SLACK_WEBHOOK_URL }}
        
     
